VS build error with not used function parameters
Building on VS fails with error:

1>Image.cpp(168): error C2220: warning treated as error - no 'object' file generated
1>Image.cpp(168): warning C4100: 'Is3Channel' : unreferenced formal parameter
1>Image.cpp(261): warning C4100: 'event' : unreferenced formal parameter
1>Image.cpp(261): warning C4100: 'events' : unreferenced formal parameter
1>Image.cpp(261): warning C4100: 'blocking' : unreferenced formal parameter

Macro UNREFERENCED_PARAMETER is used to avoid this warning treated as error.